"""
UIDetect Structured Claims Schema
==================================

Deterministic fallback claims for UIDetect's structured warning AI.

The normal free-text path is generated by Qwen in
warning_ai_consolidated.py. This module remains a safe fallback path:
it derives only confirmed facts from the backend assessment and never
creates a security finding from general knowledge.
"""

from urllib.parse import urlparse


# ==========================================================
# Small helpers
# ==========================================================

def _domain_only(website):
    """Best-effort extraction of a bare domain for optional context."""

    if not isinstance(website, str) or not website.strip():
        return "this website"

    website = website.strip()

    parsed = urlparse(
        website if "://" in website else f"https://{website}"
    )

    return parsed.netloc or website


def _as_dict(value):
    return value if isinstance(value, dict) else {}


def _int_value(value, default=0):
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _is_confirmed_primary(primary_finding):
    return (
        isinstance(primary_finding, dict)
        and primary_finding.get("confirmed") is True
    )


def _primary_text(primary_finding):
    if not _is_confirmed_primary(primary_finding):
        return ""
    return str(primary_finding.get("message", "")).strip()


# ==========================================================
# Claim derivation
# ==========================================================

def derive_security_claims(data):
    """
    Derive safe, deterministic user-facing claims from one assessment.

    The ordering follows UIDetect's confirmed finding priority:
        1. OpenPhish listed
        2. VirusTotal malicious
        3. VirusTotal suspicious
        4. Safe Browsing flagged
        5. HTTPS / SSL problems
        6. Other confirmed Primary Finding
        7. Missing security headers

    Only confirmed backend facts are used. Unknown/unavailable checks
    are never converted into findings.
    """

    if not isinstance(data, dict):
        data = {}

    claims = []

    final_posture = _as_dict(data.get("finalPosture"))
    primary_finding = final_posture.get("primaryFinding")

    recommendation_action = str(
        final_posture.get("recommendationAction", "NORMAL_CAUTION")
    ).upper()

    recommendation_reason = str(
        final_posture.get("recommendationReason", "")
    ).strip()

    interaction = str(
        data.get("interaction", "BROWSE")
    ).strip().upper()

    openphish = _as_dict(data.get("openPhish"))
    openphish_listed = openphish.get("listed") is True

    virus_total = _as_dict(data.get("virusTotal"))
    vt_malicious = _int_value(virus_total.get("malicious"), 0)
    vt_suspicious = _int_value(virus_total.get("suspicious"), 0)

    safe_browsing = str(
        data.get("safeBrowsing", "")
    ).strip().upper()

    https = data.get("https")

    ssl_data = _as_dict(data.get("ssl"))
    ssl_valid = ssl_data.get("sslValid", data.get("sslValid"))

    headers = _as_dict(data.get("securityHeaders"))
    header_checks = {
        "Strict-Transport-Security": headers.get("strict-transport-security"),
        "Content-Security-Policy": headers.get("content-security-policy"),
        "X-Frame-Options": headers.get("x-frame-options"),
        "X-Content-Type-Options": headers.get("x-content-type-options"),
        "Referrer-Policy": headers.get("referrer-policy"),
    }

    missing_headers = [
        name
        for name, value in header_checks.items()
        if value is False
    ]

    # ------------------------------------------------------
    # Determine confirmed findings in the exact priority order.
    # ------------------------------------------------------

    findings = []

    if openphish_listed:
        findings.append({
            "priority": 1,
            "id": "OPENPHISH_LISTED",
            "summary": "UIDetect found that this website is listed by OpenPhish as a phishing site.",
            "meaning": "This is a significant warning because the website is present in a phishing database.",
        })

    if vt_malicious > 0:
        findings.append({
            "priority": 2,
            "id": "VIRUSTOTAL_MALICIOUS",
            "summary": f"UIDetect found that VirusTotal has {vt_malicious} malicious detection(s) for this website.",
            "meaning": "Multiple security engines have identified a malicious result for this website.",
        })

    if vt_suspicious > 0:
        findings.append({
            "priority": 3,
            "id": "VIRUSTOTAL_SUSPICIOUS",
            "summary": f"UIDetect found {vt_suspicious} suspicious VirusTotal detection(s) for this website.",
            "meaning": "Some security engines have raised suspicion about this website, although suspicious is not the same as malicious.",
        })

    if safe_browsing in {"UNSAFE", "MALICIOUS", "PHISHING", "FLAGGED"}:
        findings.append({
            "priority": 4,
            "id": "SAFE_BROWSING_FLAGGED",
            "summary": "UIDetect found that Google Safe Browsing has flagged this website.",
            "meaning": "A browser safety service has raised a security warning about this website.",
        })

    if https is False:
        findings.append({
            "priority": 5,
            "id": "HTTPS_MISSING",
            "summary": "UIDetect found that this website does not use HTTPS.",
            "meaning": "The connection is not using the HTTPS protection detected by UIDetect.",
        })

    if ssl_valid is False:
        findings.append({
            "priority": 5,
            "id": "SSL_INVALID",
            "summary": "UIDetect found a problem with this website's SSL/TLS certificate.",
            "meaning": "The website's certificate could not be validated by UIDetect.",
        })

    primary_message = _primary_text(primary_finding)

    # Only add a generic primary finding when it is not already
    # represented by one of the specific high-priority checks above.
    if primary_message:
        primary_source = str(
            primary_finding.get("source", "")
        ).strip().lower()

        represented_sources = {
            "openphish",
            "virustotal",
            "google safe browsing",
            "https",
            "ssl",
            "ssl/tls",
            "tls",
            "security headers",
        }

        if primary_source not in represented_sources:
            findings.append({
                "priority": 6,
                "id": "PRIMARY_FINDING",
                "summary": primary_message,
                "meaning": primary_message,
            })

    if missing_headers:
        findings.append({
            "priority": 7,
            "id": "MISSING_HEADERS",
            "summary": (
                f"UIDetect found {len(missing_headers)} missing security "
                f"protection(s) on this website."
            ),
            "meaning": (
                "Some recommended security protections are not detected "
                "on this website."
            ),
        })

    findings.sort(key=lambda item: item["priority"])

    # ------------------------------------------------------
    # What Did UIDetect Find?
    # ------------------------------------------------------

    if findings:
        primary = findings[0]
        supporting = findings[1:2]

        about_text = primary["summary"]

        if supporting:
            about_text += " " + supporting[0]["summary"]

        claims.append({
            "id": "ABOUT_WEBSITE",
            "category": "about",
            "variants": [about_text],
        })

    else:
        claims.append({
            "id": "ABOUT_WEBSITE",
            "category": "about",
            "variants": [
                "UIDetect did not detect any major security problems with this website.",
            ],
        })

    # ------------------------------------------------------
    # What Does This Mean?
    # ------------------------------------------------------

    if findings:
        primary = findings[0]
        supporting = findings[1:2]

        warning_text = primary["meaning"]

        if supporting:
            warning_text += " " + supporting[0]["meaning"]

        claims.append({
            "id": "WARNING_MEANING",
            "category": "warning",
            "variants": [warning_text],
        })

    else:
        claims.append({
            "id": "WARNING_MEANING",
            "category": "warning",
            "variants": [
                "The security checks performed by UIDetect did not identify a major security concern.",
            ],
        })

    # ------------------------------------------------------
    # What Should You Do?
    # ------------------------------------------------------

    action_variants = {
        "NORMAL": [
            "You can continue with your usual browsing habits.",
        ],
        "NORMAL_CAUTION": [
            "You can continue, but keep the identified security point in mind.",
        ],
        "CAUTION": [
            "You may continue, but proceed carefully in light of the identified security concern.",
        ],
        "BLOCK": [
            "Do not continue with the current operation because the assessment requires you to stop.",
        ],
    }

    recommendation_text = action_variants.get(
        recommendation_action,
        action_variants["NORMAL_CAUTION"],
    )[0]

    # Add interaction context only when it is relevant to the current
    # action and the assessment contains a security finding. This is a
    # fallback path, so keep it concise rather than creating a large
    # matrix of interaction-specific templates.
    if findings and interaction in {
        "LOGIN", "REGISTER", "UPLOAD", "DOWNLOAD", "PAYMENT"
    }:
        if recommendation_action in {"NORMAL_CAUTION", "CAUTION"}:
            interaction_labels = {
                "LOGIN": "login details",
                "REGISTER": "registration details",
                "UPLOAD": "a file upload",
                "DOWNLOAD": "a download",
                "PAYMENT": "a payment action",
            }
            recommendation_text += (
                f" Since this involves {interaction_labels[interaction]}, "
                "apply that precaution before continuing."
            )

    # Recommendation reason is authoritative supporting context. It is
    # intentionally not copied verbatim because internal backend text
    # may contain implementation details.
    if recommendation_reason and recommendation_action == "NORMAL_CAUTION":
        # Keep the deterministic fallback concise; the authoritative
        # action already controls the recommendation tone.
        pass

    claims.append({
        "id": "RECOMMENDATION_ACTION",
        "category": "recommendation",
        "variants": [recommendation_text],
    })

    return claims
